// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    Credits: typeof import('./components/Credits.vue')['default']
    Grid: typeof import('./components/Grid.vue')['default']
    LogoSVG: typeof import('./components/LogoSVG.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheIcons: typeof import('./components/TheIcons.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    TheTermynal: typeof import('./components/TheTermynal.vue')['default']
  }
}
